--- #YAML:1.0
name:                Catalyst-Plugin-Authentication-AuthTkt
version:             0.02
abstract:            **DEPRECATED** shim for Apache::AuthTkt
license:             ~
author:              
    - Peter Karman <karman at cpan dot org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Apache::AuthTkt:               0.07
    Catalyst::Plugin::Authentication: 0.1
    Catalyst::Runtime:             0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
